const COUNTRIES = [
  {
    id: "colombia",
    name: "Colombia",
    capital: "Bogotá",
    flag: "🇨🇴",
    flagImage: "assets/flags/colombia.svg",
    region: "Suramérica",
    language: "Español y más de 60 lenguas nativas",
    greeting: "¿Qué más? / Quiubo",
    food: "Arepa",
    rhythm: "Cumbia",
    celebration: "Carnaval de Barranquilla",
    value: "La alegría compartida también puede ser una forma de hospitalidad.",
    clue: "País andino y caribeño, con enorme biodiversidad y muchas formas de hablar el español.",
    guessClues: [
      "Tiene costa en dos océanos y una cordillera dividida en tres ramas.",
      "En su vida cotidiana conviven acentos muy distintos y decenas de lenguas indígenas.",
      "Una celebración caribeña suya fue reconocida como patrimonio cultural inmaterial.",
      "Su música tradicional mezcla raíces indígenas, africanas y europeas.",
      "En su gastronomía popular aparece la arepa en muchas regiones."
    ],
    music: { tempo: 106, scale: [392, 440, 523, 587, 659], drum: "cumbia" }
  },
  {
    id: "brasil",
    name: "Brasil",
    capital: "Brasilia",
    flag: "🇧🇷",
    flagImage: "assets/flags/brasil.svg",
    region: "Suramérica",
    language: "Portugués",
    greeting: "Oi / Tudo bem?",
    food: "Feijoada",
    rhythm: "Samba",
    celebration: "Carnaval",
    value: "Celebrar juntos no borra las diferencias: las vuelve visibles y compartidas.",
    clue: "País gigante de portugués, samba, carnaval y muchas raíces afroamericanas.",
    guessClues: [
      "Es el país más extenso de América del Sur.",
      "Su lengua oficial lo diferencia de la mayoría de sus vecinos regionales.",
      "Su carnaval combina música, baile, barrios y memoria afrodescendiente.",
      "Parte de la Amazonía está dentro de su territorio.",
      "La feijoada es uno de sus platos más reconocidos."
    ],
    music: { tempo: 120, scale: [349, 392, 440, 523, 587], drum: "samba" }
  },
  {
    id: "peru",
    name: "Perú",
    capital: "Lima",
    flag: "🇵🇪",
    flagImage: "assets/flags/peru.svg",
    region: "Suramérica",
    language: "Español, quechua y aimara",
    greeting: "Allinllachu / Hola",
    food: "Ceviche",
    rhythm: "Festejo",
    celebration: "Inti Raymi",
    value: "La interculturalidad también vive en reconocer lenguas originarias actuales.",
    clue: "País andino y costero, de ceviche, quechua, Inti Raymi y ritmos afroperuanos.",
    guessClues: [
      "Su historia andina sigue viva en lenguas como el quechua y el aimara.",
      "Tiene costa, sierra y selva con tradiciones muy diferentes entre sí.",
      "Una fiesta solar de origen andino reúne memoria, música y ritualidad.",
      "Su cocina marina es reconocida internacionalmente.",
      "El festejo expresa una herencia afroperuana muy importante."
    ],
    music: { tempo: 110, scale: [330, 392, 440, 494, 659], drum: "festejo" }
  },
  {
    id: "panama",
    name: "Panamá",
    capital: "Ciudad de Panamá",
    flag: "🇵🇦",
    flagImage: "assets/flags/panama.svg",
    region: "Centroamérica",
    language: "Español y lenguas indígenas",
    greeting: "¿Qué sopa?",
    food: "Sancocho",
    rhythm: "Tamborito",
    celebration: "Carnavales",
    value: "Ser puente entre regiones también implica mezclar historias y acentos.",
    clue: "País puente entre mares y continentes, con tamborito, canal y carnavales.",
    guessClues: [
      "Su ubicación conecta América Central con América del Sur.",
      "Un paso interoceánico marcó su historia económica y cultural.",
      "Tiene tradiciones afrocaribeñas, indígenas y mestizas muy visibles.",
      "El tamborito es una expresión musical y festiva representativa.",
      "El sancocho es una sopa muy asociada con su cocina popular."
    ],
    music: { tempo: 118, scale: [330, 392, 440, 523, 587], drum: "tamborito" }
  },
  {
    id: "mexico",
    name: "México",
    capital: "Ciudad de México",
    flag: "🇲🇽",
    flagImage: "assets/flags/mexico.svg",
    region: "Norteamérica y Centroamérica cultural",
    language: "Español y lenguas originarias",
    greeting: "¿Qué onda?",
    food: "Tacos",
    rhythm: "Mariachi",
    celebration: "Día de Muertos",
    value: "La memoria de quienes estuvieron antes también hace parte de la cultura viva.",
    clue: "País de tacos, mariachi, Día de Muertos, lenguas originarias y plazas llenas de color.",
    guessClues: [
      "Su cultura actual dialoga con herencias indígenas muy antiguas.",
      "Una celebración sobre la muerte reúne memoria, altares, comida y flores.",
      "Su música de mariachi fue reconocida como patrimonio cultural inmaterial.",
      "Su capital es una de las ciudades más grandes de América.",
      "El taco es una de sus comidas más conocidas."
    ],
    music: { tempo: 112, scale: [392, 494, 523, 659, 784], drum: "mariachi" }
  },
  {
    id: "haiti",
    name: "Haití",
    capital: "Puerto Príncipe",
    flag: "🇭🇹",
    flagImage: "assets/flags/haiti.svg",
    region: "Caribe",
    language: "Criollo haitiano y francés",
    greeting: "Bonjou",
    food: "Griot",
    rhythm: "Kompa",
    celebration: "Carnaval de Jacmel",
    value: "El Caribe también habla muchas lenguas y guarda memorias de resistencia.",
    clue: "País caribeño de criollo haitiano, kompa, griot y una historia profunda de independencia.",
    guessClues: [
      "Comparte una isla caribeña con otro Estado.",
      "Su vida cotidiana usa ampliamente el criollo, además del francés.",
      "Su historia de independencia tiene un lugar central en América y el Caribe.",
      "El kompa es uno de sus sonidos populares más reconocidos.",
      "El griot es un plato tradicional asociado con celebraciones."
    ],
    music: { tempo: 104, scale: [330, 392, 440, 523, 659], drum: "kompa" }
  },
  {
    id: "ecuador",
    name: "Ecuador",
    capital: "Quito",
    flag: "🇪🇨",
    flagImage: "assets/flags/ecuador.svg",
    region: "Suramérica",
    language: "Español y kichwa",
    greeting: "Imanalla / Hola",
    food: "Encebollado",
    rhythm: "Sanjuanito",
    celebration: "Inti Raymi",
    value: "La diversidad puede estar en una misma bandera: costa, sierra, Amazonía y Galápagos.",
    clue: "País atravesado por la línea ecuatorial, con sanjuanito, kichwa y encebollado.",
    guessClues: [
      "Su nombre está ligado a una línea imaginaria del planeta.",
      "Incluye costa, sierra, Amazonía y un archipiélago famoso por su biodiversidad.",
      "El kichwa forma parte de su diversidad lingüística.",
      "El sanjuanito expresa una tradición musical andina.",
      "El encebollado es un plato muy popular en su costa."
    ],
    music: { tempo: 108, scale: [262, 330, 392, 440, 523], drum: "sanjuanito" }
  },
  {
    id: "argentina",
    name: "Argentina",
    capital: "Buenos Aires",
    flag: "🇦🇷",
    flagImage: "assets/flags/argentina.svg",
    region: "Suramérica",
    language: "Español rioplatense",
    greeting: "Che, ¿cómo andás?",
    food: "Empanadas",
    rhythm: "Tango / chacarera",
    celebration: "Día de la Tradición",
    value: "La identidad también se canta, se debate y se comparte en la mesa.",
    clue: "País del Cono Sur asociado con tango, mate, empanadas y una hinchada muy expresiva.",
    guessClues: [
      "Está en el Cono Sur y usa una forma rioplatense del español.",
      "El mate y la conversación hacen parte de muchas escenas cotidianas.",
      "El tango nació en un contexto urbano y portuario muy diverso.",
      "La chacarera expresa una tradición musical del interior.",
      "Las empanadas cambian mucho según la región."
    ],
    music: { tempo: 96, scale: [330, 392, 440, 523, 587], drum: "tango" }
  },
  {
    id: "paraguay",
    name: "Paraguay",
    capital: "Asunción",
    flag: "🇵🇾",
    flagImage: "assets/flags/paraguay.svg",
    region: "Suramérica",
    language: "Español y guaraní",
    greeting: "Mba'éichapa",
    food: "Sopa paraguaya",
    rhythm: "Polca paraguaya",
    celebration: "Fiesta de San Juan",
    value: "El bilingüismo cotidiano puede ser una fuerza de identidad compartida.",
    clue: "País bilingüe donde el guaraní está muy presente en la vida diaria.",
    guessClues: [
      "El guaraní tiene presencia cotidiana junto al español.",
      "Su capital se ubica cerca del río Paraguay.",
      "Su arpa tiene un papel muy reconocido en la música tradicional.",
      "Una comida llamada sopa no es líquida, sino sólida.",
      "La polca paraguaya hace parte de su identidad sonora."
    ],
    music: { tempo: 116, scale: [330, 392, 494, 587, 659], drum: "polca" }
  },
  {
    id: "uruguay",
    name: "Uruguay",
    capital: "Montevideo",
    flag: "🇺🇾",
    flagImage: "assets/flags/uruguay.svg",
    region: "Suramérica",
    language: "Español rioplatense",
    greeting: "Bo, ¿cómo andás?",
    food: "Chivito",
    rhythm: "Candombe",
    celebration: "Llamadas",
    value: "La memoria afrodescendiente también construye identidad nacional.",
    clue: "País rioplatense de candombe, chivito, mate y carnaval de llamadas.",
    guessClues: [
      "Es un país pequeño del Río de la Plata.",
      "Comparte con vecinos el mate y formas rioplatenses de hablar.",
      "El candombe conserva una memoria afrodescendiente fundamental.",
      "Las Llamadas son parte importante de su carnaval.",
      "El chivito es una comida muy asociada con su vida urbana."
    ],
    music: { tempo: 114, scale: [294, 349, 392, 466, 587], drum: "candombe" }
  }
];

const SCENARIOS = [
  { prompt: "Un compañero no entiende una broma del grupo. ¿Qué acción cuida mejor la convivencia?", options: ["Explicarle la broma con respeto", "Repetirla hasta que la entienda", "Cambiarlo a otro equipo"], correct: 0 },
  { prompt: "Alguien se ríe del acento de otra persona. ¿Qué respuesta es la más adecuada?", options: ["Pedir respeto por su forma de hablar", "Imitar el acento para hacer reír", "Decirle que no hable más"], correct: 0 },
  { prompt: "Una comida típica desconocida genera comentarios de rechazo. ¿Qué actitud es correcta?", options: ["Preguntar por su historia con respeto", "Hacer gestos de desagrado", "Retirar la comida de la mesa"], correct: 0 },
  { prompt: "Dos estudiantes tienen costumbres familiares diferentes. ¿Qué ayuda a conversar mejor?", options: ["Preguntar qué significa cada costumbre", "Decidir cuál costumbre es mejor", "Evitar hablar de sus familias"], correct: 0 },
  { prompt: "Un integrante no quiere hablar frente al grupo. ¿Qué puede hacer el equipo?", options: ["Ofrecerle otro rol importante", "Obligarlo a exponer de inmediato", "Dejarlo por fuera del reto"], correct: 0 },
  { prompt: "Un país solo aparece en la conversación por memes. ¿Qué ayuda a evitar estereotipos?", options: ["Buscar información más completa", "Seguir usando los memes", "Cambiar de país sin aprender"], correct: 0 },
  { prompt: "Dos personas toman todas las decisiones del equipo. ¿Qué sería juego limpio?", options: ["Repartir roles y escuchar a todos", "Seguir rápido para ganar", "Dejar que decida quien más grite"], correct: 0 },
  { prompt: "El grupo debe representar una fiesta de otro país. ¿Qué opción es más respetuosa?", options: ["Mostrar el sentido de la fiesta", "Exagerar gestos para hacer reír", "Inventar una versión sin consultar"], correct: 0 },
  { prompt: "Una bandera se usa como burla durante el juego. ¿Qué debe hacer el equipo?", options: ["Tratar el símbolo con respeto", "Seguir el chiste si causa risa", "Esconder todas las banderas"], correct: 0 },
  { prompt: "Alguien dice que todos deben actuar como la mayoría. ¿Qué idea corrige esa frase?", options: ["La convivencia requiere acuerdos mutuos", "La mayoría siempre tiene razón", "Las diferencias deben ocultarse"], correct: 0 },
  { prompt: "Un compañero pronuncia mal una palabra de otra lengua. ¿Qué ayuda más?", options: ["Corregirlo con paciencia", "Burlarse para que aprenda", "Prohibirle usar esa palabra"], correct: 0 },
  { prompt: "Una persona cuenta una tradición y varios hablan encima. ¿Qué debe hacer el grupo?", options: ["Darle tiempo para terminar", "Cambiar de tema rápidamente", "Hablar más fuerte que ella"], correct: 0 },
  { prompt: "Un equipo dice que una cultura es menos avanzada. ¿Qué respuesta es correcta?", options: ["Cuestionar esa idea con respeto", "Aceptar el comentario sin decir nada", "Repetirlo como si fuera cierto"], correct: 0 },
  { prompt: "Hay duda sobre el significado de una palabra regional. ¿Qué favorece el aprendizaje?", options: ["Preguntar cómo se usa en su región", "Elegir un significado al azar", "Prohibir usar palabras regionales"], correct: 0 },
  { prompt: "Una persona recién llegada no conoce las reglas. ¿Qué acción ayuda a integrarla?", options: ["Explicarle las reglas con calma", "Apurarla para no perder tiempo", "Cambiarla de equipo sin hablar"], correct: 0 },
  { prompt: "El grupo quiere copiar una danza sin conocerla. ¿Qué deberían hacer primero?", options: ["Preguntar o investigar su origen", "Inventar pasos parecidos", "Usarla solo para hacer reír"], correct: 0 },
  { prompt: "Alguien dice: 'Eso aquí no se hace'. ¿Qué respuesta abre mejor el diálogo?", options: ["Preguntar cómo se hace en su lugar", "Cerrar la conversación de una vez", "Imponer la costumbre local"], correct: 0 },
  { prompt: "Un estudiante mezcla dos idiomas al hablar. ¿Qué mirada es más respetuosa?", options: ["Valorar que maneja más de una lengua", "Corregir cada palabra que diga", "Pedirle que use solo español"], correct: 0 },
  { prompt: "Aparece una celebración religiosa en una respuesta. ¿Qué trato merece?", options: ["Hablar de ella con respeto", "Usarla como motivo de burla", "Reducirla a un disfraz"], correct: 0 },
  { prompt: "Un equipo gana una prueba y humilla al otro. ¿Qué valor está faltando?", options: ["Respeto en la competencia", "Más velocidad en el juego", "Más ruido al celebrar"], correct: 0 },
  { prompt: "Una persona no quiere probar una comida típica. ¿Qué respuesta respeta su decisión?", options: ["Aceptar su límite sin presionarla", "Insistir hasta que la pruebe", "Burlarse de su reacción"], correct: 0 },
  { prompt: "Alguien adivina la nacionalidad de otra persona por su apariencia. ¿Qué conviene recordar?", options: ["No se debe asumir la identidad", "La apariencia siempre basta", "Es mejor señalar sus rasgos"], correct: 0 },
  { prompt: "Un dato cultural sorprende al equipo. ¿Qué pregunta es más respetuosa?", options: ["Preguntar qué significa para ellos", "Preguntar si eso es raro allá", "Preguntar quién inventó eso"], correct: 0 },
  { prompt: "Un grupo solo conversa con sus amigos de siempre. ¿Qué mejora la integración?", options: ["Rotar parejas durante el juego", "Cerrar el grupo para avanzar", "Competir sin hablar con otros"], correct: 0 },
  { prompt: "Un compañero comparte una historia difícil de su país. ¿Qué actitud cuida la conversación?", options: ["Escuchar sin pedir detalles íntimos", "Pedir detalles para entretenerse", "Cambiar de tema sin responder"], correct: 0 },
  { prompt: "Una tradición se presenta como si todos la vivieran igual. ¿Qué aclaración hace falta?", options: ["Decir que puede variar por región", "Presentarla como única verdad", "Elegir una versión y cerrar"], correct: 0 },
  { prompt: "Alguien usa una palabra ofensiva sin saberlo. ¿Qué ayuda a corregir la situación?", options: ["Explicar por qué puede herir", "Atacarlo frente a todos", "Repetir la palabra varias veces"], correct: 0 },
  { prompt: "El equipo no entiende una práctica cultural. ¿Qué paso es más responsable?", options: ["Pedir contexto antes de opinar", "Juzgarla de inmediato", "Descartarla por ser diferente"], correct: 0 },
  { prompt: "Una persona queda siempre encargada de traducir. ¿Qué problema puede aparecer?", options: ["Se le carga demasiado trabajo", "El equipo recibe demasiada ayuda", "La actividad queda muy silenciosa"], correct: 0 },
  { prompt: "Un símbolo indígena se usa como simple adorno. ¿Qué debe revisar el equipo?", options: ["Si se usa con respeto y contexto", "Si combina con los colores", "Si ocupa suficiente espacio"], correct: 0 },
  { prompt: "Un estudiante cambia de opinión después de escuchar a otro. ¿Qué valor muestra?", options: ["Apertura para aprender", "Debilidad frente al grupo", "Falta de opinión propia"], correct: 0 },
  { prompt: "Una regla del juego deja por fuera a alguien. ¿Qué debería hacer el equipo?", options: ["Ajustar la regla para incluirlo", "Culparlo por no adaptarse", "Seguir igual para ahorrar tiempo"], correct: 0 },
  { prompt: "Alguien cree conocer un país solo por una serie. ¿Qué le falta hacer?", options: ["Comparar con otras fuentes", "Ver más capítulos de la serie", "Hablar con más seguridad"], correct: 0 },
  { prompt: "Un equipo confunde dos países vecinos. ¿Qué actitud enseña sin burlarse?", options: ["Corregir con datos claros", "Reírse del error del equipo", "Dejar el error sin explicar"], correct: 0 },
  { prompt: "Una persona pide que no toquen su cabello o su ropa. ¿Qué corresponde hacer?", options: ["Respetar su límite personal", "Insistir de forma amable", "Tomar una foto sin tocar"], correct: 0 },
  { prompt: "El grupo convierte una lengua en chiste. ¿Qué debe corregirse?", options: ["Tratarla como una lengua valiosa", "Repetirla para que suene graciosa", "Hablarla rápido sin entender"], correct: 0 },
  { prompt: "Alguien dice que una comida huele mal. ¿Qué alternativa cuida la convivencia?", options: ["Hablar con respeto y cuidado", "Taparse la nariz frente a todos", "Pedir que retiren el plato"], correct: 0 },
  { prompt: "Un compañero explica una tradición y lo interrumpen varias veces. ¿Qué ayuda?", options: ["Respetar turnos de palabra", "Competir por hablar primero", "Hacer menos preguntas"], correct: 0 },
  { prompt: "Una opinión cultural incomoda al grupo. ¿Qué conviene hacer primero?", options: ["Pedir razones y escuchar", "Reírse para bajar tensión", "Cancelar toda la conversación"], correct: 0 },
  { prompt: "Una persona se equivoca al ubicar un país. ¿Qué respuesta enseña mejor?", options: ["Mostrar el mapa con respeto", "Hacer burla del error", "Quitarle puntos extra"], correct: 0 },
  { prompt: "El equipo llama 'normal' solo a su propia costumbre. ¿Qué conviene recordar?", options: ["Cada cultura tiene su forma", "Lo propio siempre es normal", "Comparar para ver cuál gana"], correct: 0 },
  { prompt: "Un participante habla poco por timidez. ¿Qué forma de participación puede servir?", options: ["Hacer una vocería compartida", "Exigirle una exposición solo", "Dejarlo en silencio todo el juego"], correct: 0 },
  { prompt: "Una historia personal se empieza a contar como chisme. ¿Qué límite es necesario?", options: ["Cuidar la privacidad de la persona", "Pedir más detalles al grupo", "Repetirla en otra estación"], correct: 0 },
  { prompt: "Un equipo quiere ganar ignorando los acuerdos. ¿Qué valor se pierde?", options: ["Cooperación con el grupo", "Rapidez para responder", "Estrategia de competencia"], correct: 0 },
  { prompt: "Una persona corrige un estereotipo sobre su país. ¿Qué debe hacer el grupo?", options: ["Escuchar y ajustar la idea", "Defender el chiste anterior", "Cambiar de mesa sin responder"], correct: 0 },
  { prompt: "Un país se reduce solo a fútbol. ¿Qué amplía mejor la mirada?", options: ["Hablar de su vida cotidiana", "Hablar solo de resultados", "Comparar camisetas y uniformes"], correct: 0 },
  { prompt: "Una palabra regional causa risa en el equipo. ¿Qué gesto cuida el respeto?", options: ["Preguntar su significado", "Repetirla como burla", "Imitar la voz de quien la dijo"], correct: 0 },
  { prompt: "Alguien no participa porque no entendió una instrucción. ¿Qué debe hacer el equipo?", options: ["Explicarla de nuevo con calma", "Avanzar sin esa persona", "Bajarle puntos al equipo"], correct: 0 },
  { prompt: "Una diferencia cultural se vuelve discusión. ¿Qué paso inicial ayuda más?", options: ["Escuchar antes de responder", "Ganar la discusión rápido", "Evitar cualquier diálogo"], correct: 0 },
  { prompt: "Un equipo celebra el error de otro grupo. ¿Qué sería más respetuoso?", options: ["Animar y aprender del error", "Gritar más fuerte la burla", "Restar valor al otro equipo"], correct: 0 }
];
